[tool.black]
line-length = 88
target-version = ['py36', 'py37']
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.pytest_cache
    | build
    | dist
  )/
)
'''
[tool.pytest.ini_options]
addopts = "-W error --mypy --ignore flair/data_fetcher.py --ignore flair/embeddings/legacy.py --isort"
markers = [
    "integration",
]
[tool.mypy]
exclude = "flair/data_fetcher.py|flair/embeddings/legacy.py"
ignore_missing_imports = true

[tool.isort]
profile = "black"