[tool.black]
line-length = 88
target-version = ['py36', 'py37']
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.pytest_cache
    | build
    | dist
  )/
)
'''
[tool.pytest.ini_options]
addopts = "-W error"
markers = [
    "integration",
]